version: "3"

services:
  plain:
    image: a-service
    build: "."
    ports:
      - "4040:4040"
    expose: 
      - "4040"
    environment:
      - PORT=4040
  aspecto:
    image: a-service
    ports:
      - "4041:4041"
    expose: 
      - "4041"
    environment:
      - PORT=4041
      - ASPECTO=true
  otel:
    image: a-service
    ports:
      - "4042:4042"
    expose: 
      - "4042"
    environment:
      - PORT=4042
      - OTEL=true
  

